/**
 * Rule-based financial insights. Every number comes from the analytics engine;
 * nothing is generated by a language model, so nothing can be invented.
 * (An LLM may optionally *rephrase* these, but the facts are fixed here.)
 */
import type { TxnLite } from "../domain/types";
import { categoryLabel } from "../domain/categories";
import { addDays, addMonths, daysBetween, financialMonthRange, type ISODate } from "../util/dates";
import { formatINR, pct, round2, sum } from "../util/money";
import { calculateCategorySpend, calculateSummary, detectAnomalies, isSpending } from "./engine";
import { monthlyCommitments, type BudgetVariance, type ManualObligation, type UpcomingItem } from "./planning";
import type { RecurringSeries } from "./recurring";

export type Severity = "info" | "positive" | "warning" | "alert";

export interface Insight {
  kind: string;
  severity: Severity;
  title: string;
  body: string;
  data?: Record<string, unknown>;
}

export function generateInsights(opts: {
  txns: TxnLite[];
  asOf: ISODate;
  monthStartDay?: number;
  budgets?: BudgetVariance[];
  series?: RecurringSeries[];
  manual?: ManualObligation[];
  upcoming?: UpcomingItem[];
}): Insight[] {
  const { txns, asOf } = opts;
  const startDay = opts.monthStartDay ?? 1;
  const out: Insight[] = [];
  if (!txns.length) return out;

  const range = financialMonthRange(asOf, startDay);
  const elapsed = daysBetween(range.from, asOf);
  const thisMonth = txns.filter((t) => t.date >= range.from && t.date <= range.to);
  const prevFrom = addMonths(range.from, -1, startDay > 1 ? startDay : 1);
  const prevRange = financialMonthRange(prevFrom, startDay);
  const prevSamePoint = txns.filter((t) => t.date >= prevRange.from && t.date <= addDays(prevRange.from, elapsed));
  const prevFull = txns.filter((t) => t.date >= prevRange.from && t.date <= prevRange.to);

  // Data freshness
  const lastDate = txns.reduce((a, t) => (t.date > a ? t.date : a), txns[0].date);
  const staleDays = daysBetween(lastDate, asOf);
  if (staleDays > 40) {
    out.push({
      kind: "stale_data",
      severity: "warning",
      title: "Your data may be out of date",
      body: `The latest transaction on record is from ${lastDate} (${staleDays} days ago). Upload a newer statement so analytics and forecasts reflect reality.`,
      data: { lastDate, staleDays },
    });
  }

  // Spending vs previous month (same point in month)
  const spentNow = sum(thisMonth.filter(isSpending).map((t) => t.debit));
  const spentPrev = sum(prevSamePoint.filter(isSpending).map((t) => t.debit));
  if (thisMonth.length && spentPrev > 0 && elapsed >= 3) {
    const change = pct(Math.abs(spentNow - spentPrev), spentPrev);
    const up = spentNow > spentPrev;
    out.push({
      kind: "mom_change",
      severity: up && change >= 20 ? "warning" : up ? "info" : "positive",
      title: up ? `Spending is up ${change}% vs last month` : `Spending is down ${change}% vs last month`,
      body: `So far this month you've spent ${formatINR(spentNow)}, compared with ${formatINR(spentPrev)} at the same point last month.`,
      data: { spentNow, spentPrev, change },
    });
  }

  // Top category
  const cats = calculateCategorySpend(thisMonth);
  if (cats[0] && spentNow > 0) {
    out.push({
      kind: "top_category",
      severity: "info",
      title: `${categoryLabel(cats[0].category)} is your biggest category this month`,
      body: `${formatINR(cats[0].amount)} (${cats[0].pct}% of spending) went to ${categoryLabel(cats[0].category)}${cats[0].subcategories[0] ? `, mostly ${cats[0].subcategories[0].name}` : ""}.`,
      data: { category: cats[0].category, amount: cats[0].amount },
    });
  }

  // Savings rate for last full month
  const prevSummary = calculateSummary(prevFull);
  if (prevSummary.savingsRate !== null && prevFull.length) {
    const r = prevSummary.savingsRate;
    out.push({
      kind: "savings_rate",
      severity: r >= 20 ? "positive" : r >= 0 ? "info" : "warning",
      title: r >= 0 ? `You kept ${r}% of income last month` : "Last month's spending exceeded income",
      body:
        r >= 0
          ? `Income ${formatINR(prevSummary.income)} vs net spending ${formatINR(prevSummary.netSpending)} left an estimated ${formatINR(prevSummary.savings)}.`
          : `Income was ${formatINR(prevSummary.income)} but net spending was ${formatINR(prevSummary.netSpending)}.`,
      data: { savingsRate: r },
    });
  }

  // Budgets
  for (const b of opts.budgets ?? []) {
    if (b.status === "ok") continue;
    out.push({
      kind: "budget",
      severity: b.status === "over" ? "alert" : "warning",
      title: `${categoryLabel(b.category)} budget: ${b.status === "over" ? "exceeded" : b.status === "projected_over" ? "on pace to exceed" : "nearly used"}`,
      body: `${formatINR(b.actual)} of ${formatINR(b.budget)} used (${b.pctUsed}%). ${b.message}`,
      data: { category: b.category, pctUsed: b.pctUsed },
    });
  }

  // Unusual transactions (last 30 days)
  const anomalies = detectAnomalies(txns).filter((a) => a.txn.date >= addDays(asOf, -30));
  if (anomalies.length) {
    const a = anomalies[0];
    out.push({
      kind: "anomaly",
      severity: "warning",
      title: `${anomalies.length} unusual transaction${anomalies.length > 1 ? "s" : ""} in the last 30 days`,
      body: `${a.txn.merchant} on ${a.txn.date}: ${formatINR(a.txn.amount)} - ${a.reason}.`,
      data: { count: anomalies.length, top: a.txn.id },
    });
  }

  // Recurring commitments
  if (opts.series?.length || opts.manual?.length) {
    const commit = monthlyCommitments(opts.series ?? [], opts.manual ?? []);
    const avgIncome = calculateSummary(prevFull).income;
    if (commit > 0) {
      out.push({
        kind: "commitments",
        severity: "info",
        title: `Recurring payments total about ${formatINR(commit)}/month`,
        body: avgIncome > 0 ? `That's roughly ${pct(commit, avgIncome)}% of last month's income (estimate based on detected and manual recurring payments).` : "Estimate based on detected and manually entered recurring payments.",
        data: { commitments: commit },
      });
    }
  }

  // Upcoming
  const next7 = (opts.upcoming ?? []).filter((u) => u.kind === "expense" && u.date <= addDays(asOf, 7));
  if (next7.length) {
    out.push({
      kind: "upcoming",
      severity: "info",
      title: `${next7.length} payment${next7.length > 1 ? "s" : ""} expected in the next 7 days`,
      body: `Estimated ${formatINR(sum(next7.map((u) => u.amount)))} - ${next7.slice(0, 3).map((u) => u.name).join(", ")}${next7.length > 3 ? "…" : ""}.`,
      data: { total: round2(sum(next7.map((u) => u.amount))) },
    });
  }

  // Fees
  const fees = sum(txns.filter((t) => t.category === "BANKING FEES" && t.date >= addDays(asOf, -90)).map((t) => t.debit));
  if (fees > 0) {
    out.push({ kind: "fees", severity: "info", title: `${formatINR(fees)} in bank charges over 90 days`, body: "Small fees add up - check for avoidable charges such as SMS alerts or minimum balance penalties.", data: { fees } });
  }

  return out;
}
