import { route } from "@/lib/auth/guard";
import { getInsights } from "@/lib/services/intelligence";

/** Deterministic insights feed (newest first). Recomputed from the ledger on every change; nothing is generated by an LLM. */
export const GET = route(async ({ user }) => ({ insights: getInsights(user.id) }));
